### ISSUE TITLE
Presa in carico per ogni trasferimento competenza

### ISSUE THREAD

**Issue by francesco-filicetti** [UniversitaDellaCalabria/uniTicket#11]
Quando viene assegnata/trasferita una competenza, l'operatore del nuovo ufficio prende in carico il ticket, esattamente come avviene la prima volta.
Se l'operatore trasferisce la competenza ad un ufficio di cui fa già parte il ticket risulta già preso in carico.

**Comment by peppelinux** [comment]
Implementata in release v1.0.0
