### ISSUE TITLE
Nuove Features - richieste da Dices

### ISSUE THREAD

**Issue by peppelinux** [UniversitaDellaCalabria/uniTicket#12]
- Possibilità di mandare "rimbalzare" indietro un ticket all'interno di una soglia (1 volta)
- Disabilita notifica via email mediante token di conferma inviato via email

**Comment by peppelinux** [comment]
@francesco-filicetti queste sono deprecabili oppure parzialmente commitate?

**Comment by francesco-filicetti** [comment]
@peppelinux ci penso. Quella del singolo rimbalzo sul trasferimento di competenza mi stimola di più. L'altra (token email) la considero deprecata, l'utente ha facoltà di scegliere da frontend.

**Comment by peppelinux** [comment]
possiamo chiuderlo o ci sono ancora idee buone a riguardo?
