### ISSUE TITLE
richiesta inserimento argea sardegna in "la mia amministrazione lo usa"

### ISSUE THREAD

**Issue by madmaddina** [UniversitaDellaCalabria/uniTicket#120]
Buongiorno, 

con la presente si richiede l'inserimento di Argea Sardegna nella sezione "la mia amministrazione lo usa" su developers italia per il software Uniticket. 

I dati sono i seguenti:
Denominazione "ARGEA Sardegna"
Codice IPA argea
Codice univoco AOO A3D2739

Grazie, 
Maddalena Meli

**Comment by francesco-filicetti** [comment]
Ciao Maddalena,
sarebbe stato meglio aprire una Pull request ma non c'è problema.
Ho modificato il publiccode.yml e ora ARGEA Sardegna è ufficialmente nell'elenco degli enti che usano uniTicket.
https://github.com/UniversitaDellaCalabria/uniTicket/commit/07ce1ba9d4c9cf041487e4e9cc99a2f504249a29
Grazie, a presto
