### ISSUE TITLE
Messaggio personalizzabile in caso di 404 di un modulo di richiesta

### ISSUE THREAD

**Issue by peppelinux** [UniversitaDellaCalabria/uniTicket#14]
Caso d'uso, iniziativa donazioni x Covid.
Gli utenti che hanno dimenticato la deadline e che tentano di accedere in ritardo, ovvero dopo la scadenza dell'iniziativa (tipo di richiesta) ottengono una pagina di Errore 404, come consueto.

Sarebbe opportuno, al fine di evitare inutili rimbalzi su helpdesk, implementare la possibilità di personalizzare un avviso di 404 all'interno della configurazione del modulo.

Esempio sul caso d'uso:
Questa iniziativa è scaduta (il codice 404 permarrebbe nella tipologia di Http Response)

**Comment by francesco-filicetti** [comment]
Solved with these two commits: 

[[1](https://github.com/UniversitaDellaCalabria/uniTicket/commit/2f11e65add4ab3a6a34e3f9d6007188b907de569)]

[[2](https://github.com/UniversitaDellaCalabria/uniTicket/commit/532af134c02e8ca31c85d59e4030a3b78b45f8b8)]
