### ISSUE TITLE
Le URL delle immagini sono esterne al repository

### ISSUE THREAD

**Issue by libremente** [UniversitaDellaCalabria/uniTicket#17]
Buongiorno @francesco-filicetti,
purtroppo il validatore del publiccode.yml restituisce ancora un errore. 
```
validation ko:
description/it/screenshots: Absolute URL (https://uniticket.readthedocs.io/it/latest/_images/dashboard1.png) is outside the repository (https://raw.githubusercontent.com/UniversitaDellaCalabria/uniTicket/master/) 
```
Questo implica che tutti gli screenshot (ad esempio https://github.com/UniversitaDellaCalabria/uniTicket/blob/master/publiccode.yml#L109) devono essere interni al repository, come fatto ad esempio con il primo screenshot.

Resto a disposizione, grazie!

**Comment by francesco-filicetti** [comment]
Ciao,
okay, non ero a conoscenza di questa regola.
Grazie!!

**Comment by francesco-filicetti** [comment]
Fixato qui https://github.com/UniversitaDellaCalabria/uniTicket/commit/32f7c1e663b13137c2c9d240c6c0594ed0da092b
