### ISSUE TITLE
Presets configurabili di risposta/motivazione chiusura ticket

### ISSUE THREAD

**Issue by peppelinux** [UniversitaDellaCalabria/uniTicket#18]
I colleghi dell'helpdesk hanno creato un documento per copia incollare di volta in volta le risposte.

Potremmo creare un set di risposte default (problema risolto, a presto e via dicendo) e inoltre la possibilità, per ogni modulo di richiesta, di poterne aggiungere di nuove.

In questo caso una select e un evento JS farebbero si di replicare la risposta selezionata nel box delle motivazioni/comunicazioni, così che l'operatore possa in aggiunta modificarle prima dell'invio.

**Comment by francesco-filicetti** [comment]
Solved here https://github.com/UniversitaDellaCalabria/uniTicket/commit/854b1ffa52d4628d75ddd773616ba31a4548b6c8
