### ISSUE TITLE
Stato chiusura ticket

### ISSUE THREAD

**Issue by peppelinux** [UniversitaDellaCalabria/uniTicket#20]
Aggiungere uno stato codificato alla chiusura di ogni ticket:

-1, Rifiutato
 0, Non risolto
 1, Risolto con successo
 2, Non definito

Questo faciliterebbe la lettura degli esiti di chiusura di un ticket ad eventuali consumatori del servizio via API (bot)

**Comment by francesco-filicetti** [comment]
Solved here https://github.com/UniversitaDellaCalabria/uniTicket/commit/b73ee19860ab9313096ba41af76e713d89acd6fd

Use this script to set the status "1" (successful) on all tickets already closed

    from uni_ticket.models import Task, Ticket

    tickets = Ticket.objects.filter(is_closed=True)
    for ticket in tickets:
        ticket.closing_status = 1
        ticket.save(update_fields=['closing_status'])

    tasks = Task.objects.filter(is_closed=True)
    for task in tasks:
        task.closing_status = 1
        task.save(update_fields=['closing_status'])
