### ISSUE TITLE
Colore del link

### ISSUE THREAD

**Issue by peppelinux** [UniversitaDellaCalabria/uniTicket#22]
![Schermata a 2020-07-08 15-23-45](https://user-images.githubusercontent.com/1297620/86924120-501e2d00-c12f-11ea-9644-7b03a59f033f.png)

Il colore del link "Clicca qui per tornare alle richieste assegnate" dovrebbe essere di colore diverso dal rosso, magari verde, per evitare che il messaggio possa essere confuso con un messaggio di errore.

**Comment by francesco-filicetti** [comment]
solved here https://github.com/UniversitaDellaCalabria/uniTicket/commit/818ef98e82e52c45ea05cadca9e4d4f42eed666f
