### ISSUE TITLE
Protocollo Informatico

### ISSUE THREAD

**Issue by peppelinux** [UniversitaDellaCalabria/uniTicket#24]
- is_active editabile massivamente in change_list (modeladmin) come:
````
list_display = (..., 'is_active')
    list_editable = ('is_active',) 
````
- includere nella select dei titolati anche, tra parentesi, il codice, es. "Balh blah [9095]"
- fix campo email on save, se manca il sistema da errore in rosso per assenza valore

**Comment by francesco-filicetti** [comment]
solved here https://github.com/UniversitaDellaCalabria/uniTicket/commit/7d21f6c4389849cef4a94a8604bca87034e0adca
