### ISSUE TITLE
Periodo di validità del modulo

### ISSUE THREAD

**Issue by dodaroe** [UniversitaDellaCalabria/uniTicket#30]
Impostare il periodo di validità di un modulo in modo da poter disattivare il modulo al giorno e all'ora esatta della scadenza.

**Comment by peppelinux** [comment]
Buona feature, qualcosa tipo:

publish_start_date
publish_end_date

@francesco-filicetti che ne pensi? Semantica?
Bisogna capire se applicarlo al modulo o alla categoria di richiesta, problemabilmente a quest'ultima.
@dodaroe che ne pensi?

**Comment by francesco-filicetti** [comment]
Direi alla categoria.
Grazie @dodaroe

**Comment by dodaroe** [comment]
Si alla categoria di richiesta sarebbe perfetto.

**Comment by peppelinux** [comment]
> Direi alla categoria.
> Grazie @dodaroe

allora semplicemente start_date e end_date se fossimo d'accordo

**Comment by francesco-filicetti** [comment]
rilasciata v1.4.0 con, tra le altre, questa nuova funzionalità

https://github.com/UniversitaDellaCalabria/uniTicket/releases/tag/v1.4.0

**Comment by peppelinux** [comment]
Felicemente chiudiamo la issue, grazie
