### ISSUE TITLE
Formattazione campo "inserimenti multipli" a tabella

### ISSUE THREAD

**Issue by dodaroe** [UniversitaDellaCalabria/uniTicket#31]
Formattare il campo "inserimento multipli" a tabella in modo da visualizzare i valori in colonna e non in riga.
Renderebbe più leggibile il modulo.

**Comment by peppelinux** [comment]
Non credo che funzioni, gli incollonamenti su mobile sono un disastro e in principio era proprio così, poi abbiamo deciso di fare TabularInline, righe, tale da ottenere "infinite" righe (campi di inserimento) senza rovinare il layout. Ad oggi è il male minore quando i moduli diventano densi.

Questa risposta non è definitiva, possiamo continuare a pensarci su, propopi un esempio, vediamo di capire che gradi di libertà potremmo avere

**Comment by dodaroe** [comment]
In effetti su mobile le righe sono molto meglio. L'esempio è questo:

richiesta di convalida esami, gli studenti devono inserire: codice insegnamento, denominazione insegnamento, cordo di laurea, voto, data. 
Non sarebbe un problema se gli insegnamenti da convalidare fossero due, tre o quattro ma quando cominciano ad essere di più diventa un problema. 
Oppure dipotrebbe far in modo che sul pdf si veda in tabella? in questo modo l'utente potrebbe generare il pdf e visualizzarlo in tabella

**Comment by peppelinux** [comment]
Hai un esempio nel ticket ICT guest.unical.it che segue questi caso d'uso

**Comment by dodaroe** [comment]
Ho creato dei file excel con le informazioni che mi interessano. Lo studente scarica il file nel link che ho messo in pre-text e poi, dopo averlo compilato, lo ricarica nel modulo. Potete vedere un esempio in richiesta convalida esami o richiesta variazione piano di studi

**Comment by peppelinux** [comment]
Grande!
