### ISSUE TITLE
Sezione riservata Operatori

### ISSUE THREAD

**Issue by dodaroe** [UniversitaDellaCalabria/uniTicket#32]
Sarebbe, secondo me, il caso di creare una sezione riservata agli operatori che consenta il caricamento degli atti inerenti alla richiesta e che sia visibile solo agli operatori. Ad esempio, l'istanza di passaggio viene acquisita in prima battuta dall'ufficio didatticao che la porta in consiglio. Qui viene generato il verbale e la tabella delle convalide. Poi l'istanza passa in segreteria studenti per la lavorazione finale. Quando si trasferisce la competenza dall'ufficio didattico  alla segreteria studenti l'operatore dovrebbe caricare il verbale e tutto la documentazione che riguarda il singolo utente direttamente in ticket ma l'utente non dovrebbe visualizzare tali file poichè potrebbero contenere informazioni di altre richieste.

**Comment by francesco-filicetti** [comment]
Bella osservazione. Pensavo che, invece di aggiungere nuovi elementi specializzati, potremmo sfruttare le Attività:

- inseriamo un nuovo parametro booleano "visible_to_user" per ogni attività: se è True, l'utente che ha aperto il ticket visualizzerà l'attività (come è ora); se è False, solo gli operatori potranno visualizzarla;

Considerando che:
- le attività già consentono l'upload di un allegato;
- ogni operazione su un'attività viene tracciata nei log del ticket (creazione, modifica, eliminazione);

secondo me abbiamo già tutti gli elementi per gestire il caso d'uso.

@peppelinux @dodaroe cosa ne pensate? L'unica modifica sarebbe applicare il privilegio di visibilità agli utenti.

**Comment by dodaroe** [comment]
Si già applicando i provilegi di visibilità, secondo me, risolviamo. Buona soluzione!

**Comment by francesco-filicetti** [comment]
Fatto.
Se il parametro "Visibile dall'utente" è False, questa sarà accessibile ai soli operatori.
L'utente vedrà solo gli eventi di log e l'attività nella lista del ticket, ma non potrà consultarne i dettagli o scaricare eventuali allegati

**Comment by dodaroe** [comment]
Ottimo! grande!
