### ISSUE TITLE
Possibilità di un Manager di abilitare altri manager 

### ISSUE THREAD

**Issue by peppelinux** [UniversitaDellaCalabria/uniTicket#33]
Nella configurazione della struttura.
Che ne pensate?

**Comment by francesco-filicetti** [comment]
Selezionando il nuovo manager dall'elenco degli operatori attualmente afferenti a un ufficio della struttura o dall'elenco di tutti gli utenti presenti sul sistema?

**Comment by peppelinux** [comment]
mmhhh... elenco tutti gli utenti presenti a sistema con filtro select
Stessa cosa per gli operatori

**Comment by francesco-filicetti** [comment]
bene. quindi permettiamo ai manager di creare sia nuovi operatori che nuovi manager.
il manager si crea dalla configurazione della struttura.
l'operatore già nell'ufficio di destinazione.
ok?

**Comment by peppelinux** [comment]
right

**Comment by dodaroe** [comment]
E' una ottima idea. Così in caso di necessità le strutture in autonomia possono anche nominare un manager provvisorio.
Sarebbe ottimo anche riuscire a creare nuovi operatori come suggerisce Francesco.

**Comment by francesco-filicetti** [comment]
aggiornamento effettuato.
- un manager può ora creare nuovi utenti manager per la sua struttura accedendo alla sezione **Configurazione/Manager di struttura** selezionandoli dalla lista degli utenti registrati sul sistema;
- un manager può assegnare, per ogni ufficio, nuovi operatori selezionandoli dalla lista degli utenti registrati sul sistema.
