### ISSUE TITLE
Superamento limitazione di precompilazione

### ISSUE THREAD

**Issue by dodaroe** [UniversitaDellaCalabria/uniTicket#34]
Quando un utente precompila la richiesta e la stessa viene poi inviata da un altro utente, il "precompilatore" non può più efferttuare altre operazioni. Ad esempio richiesta lavoro di tesi, viene precompilato dallo studente e inviato dal docente relatore. E' stato chiesto allo studente, tramite messaggistica interna, di allegare un auto certificazione degli esami ma il sistema ha restituito il seguente messaggio: "Impossibile effettuare l'operazione. Nonostante tu abbia precompilato la richiesta è l'utente .... che l'ha sottomessa".
Forse sarebbe meglio superare questa limitazione. Che ne pensate?

**Comment by peppelinux** [comment]
Il pregio e allo stesso tempo il difetto della precompilazione è che questa è stateless, ovvero non viene memorizzata sul sistema e viaggia criptata mediante link.

Siamo ancora indecisi se modificare questo comportamento oppure lasciare così, diciamo che non stiamo avendo la testa libera per decidere. Ad ogni modo gli allegati possono essere inclusi nella email inviata per condividere il link della precompilazione, per adesso.

**Comment by francesco-filicetti** [comment]
Effettuato un aggiornamento che consente agli utenti che precompilano una richiesta di inviare messaggi agli operatori.
Restano negati i permessi di modifica, chiusura ed eliminazione della richiesta.

**Comment by dodaroe** [comment]
Grande Francesco. Diciamo che secondo me può restare così. Del resto credo che la responsabilità alla fine sia di chi invia ed è giusto che è chi invia ad avere la possibilità di modificare o eliminare la richiesta, mentre chi precompila può almeno inviare messaggi per chiedere informazioni o aggiungere della documentazione mancante.
Vi faccio un esempio. Per noi il modulo che invia il docente (e che lo studente precompila) equivale ad una firma: come a dire: "ok ho controllato, ho modificato te lo firmo e lo invio". Quindi è solo chi mette la "firma" finale che poi dovrebbe avere la possibilità di modificare o eliminare qualcosa "firmata" da lui. Che dite?

**Comment by peppelinux** [comment]
> Effettuato un aggiornamento che consente agli utenti che precompilano una richiesta di inviare messaggi agli operatori.
> Restano negati i permessi di modifica, chiusura ed eliminazione della richiesta.

Questo davamo per scontato che potesse avvenire via email, in fase di condivisione

**Comment by peppelinux** [comment]
> Grande Francesco. Diciamo che secondo me può restare così. Del resto credo che la responsabilità alla fine sia di chi invia ed è giusto che è chi invia ad avere la possibilità di modificare o eliminare la richiesta, mentre chi precompila può almeno inviare messaggi per chiedere informazioni o aggiungere della documentazione mancante.
> Vi faccio un esempio. Per noi il modulo che invia il docente (e che lo studente precompila) equivale ad una firma: come a dire: "ok ho controllato, ho modificato te lo firmo e lo invio". Quindi è solo chi mette la "firma" finale che poi dovrebbe avere la possibilità di modificare o eliminare qualcosa "firmata" da lui. Che dite?

Così già è, correggetemi se sbaglio

**Comment by francesco-filicetti** [comment]
Si, è cosi. 
Con l'ultimo aggiornamento consentiamo esclusivamente all'utente che precompila di inviare messaggi agli operatori.

**Comment by francesco-filicetti** [comment]
Allora chiudo :)
