### ISSUE TITLE
Problema link - Dati non consistenti

### ISSUE THREAD

**Issue by dodaroe** [UniversitaDellaCalabria/uniTicket#35]
Segnalo che capita, a volta, che quando si clicca sul link generato il sistema restituisce un errore di dati non consistenti.
Tuttavia se invece di cliccare sul link, si copia l'url come testo e lo si incolla nella barra degli indirizzi il tutto funziona correttamente.

**Comment by peppelinux** [comment]
Parli del sistema di delega?

**Comment by dodaroe** [comment]
Sì esatto

**Comment by peppelinux** [comment]
Strano, non vorrei che ci fosse qualche componente o estenzione all'interno del browser che vada a invalidare l'url.
Ne abbiamo visto di anomalie di questo tipo, tienici un occhio sopra e casomai facciamo VC all'occorrenza, così da constatarlo noi in diretta e vedere che determinanti ci possano essere. Grazie per il feedback

**Comment by francesco-filicetti** [comment]
L'URL generato non mi pare sia cliccabile, è inserito in un text field che lo renderizza come testo.

**Comment by peppelinux** [comment]
Credo che sia una estensione del browser che riconosce il testo come url e lo rende interattivo ma di fatto si perderebbe alcuni dati, data la lunghezza variabile degli argomenti codificati nell'url

**Comment by dodaroe** [comment]
Vi ho inviato una mail con un link incriminato

**Comment by peppelinux** [comment]
Il link è inconsistente, ovvero non supera la validazione di uniticket, significa che è stato in qualche modo corrotto nel contenuto.
Indagherei su come questo sia stato riportato dalla pagina alla email, per la condivisione, tutto qui, lì avremmo contezza di come in fase di copia/incolla l'informazione perda la propria integrità

**Comment by peppelinux** [comment]
@dodaroe grazie per il contributo, credo che questa sia un falso positivo dovuto ad una cattiva interpretazione del link da parte del client email oppure una qualche forma di tampering/hjack. 

possiamo chiuderla con serenità
