### ISSUE TITLE
problema full export

### ISSUE THREAD

**Issue by tricolig** [UniversitaDellaCalabria/uniTicket#40]
Per quanto riguarda gli inserimenti multipli, i campi che hanno un nome in cui c'è il carattere apostrofo (es. "Sostenuto presso l'università") non vengono riportati nella full export.

**Comment by francesco-filicetti** [comment]
solved fixing [django-form-builder](https://github.com/UniversitaDellaCalabria/django-form-builder) here https://github.com/UniversitaDellaCalabria/django-form-builder/commit/d5f229170006a1ed1447a1a40dace702b1d97c83

**Comment by francesco-filicetti** [comment]
imporove solving here https://github.com/UniversitaDellaCalabria/django-form-builder/commit/0318ab116d4403f4144b56835a97044a11ef4ed6
