### ISSUE TITLE
Errore nella creazione dell'immagine

### ISSUE THREAD

**Issue by alidaisolani** [UniversitaDellaCalabria/uniTicket#56]
Salve,
  siamo della Scuola Normale Superiore di Pisa e, in ottica di riuso, stavamo provando a installare il vostro sistema di ticketing. 
Abbiamo, quindi, provato a creare l'immagine docker con il comando 
"docker image build --tag uniticket:v1 ." 
dopo aver clonato il codice sorgente. 

La creazione dell'immagine restituisce però il seguente errore:
OSError: cannot load library 'gobject-2.0': gobject-2.0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0'

Cosa stiamo sbagliando?
Grazie in anticipo,
Alida

**Comment by peppelinux** [comment]
Ciao @alidaisolani 
temo che questo errore derivi dal docker in ambiente Windows 10, confermi?
Prova a farlo da una macchina virtuale GNU/Linux, sono certo che andrà tutto bene.

facci sapere

**Comment by alidaisolani** [comment]
Ciao Giuseppe e grazie per il rapido riscontro.
In realtà @Claudio BATTAGLINO , che ci legge in copia, ha risolto con
questa modifica:
1) Modificare riga 16 di Dockerfile aggiungendo: "libgtk2.0-0" alle
librerie installate nel container.

Inoltre ha anche fatto queste due ulteriori modifiche:
2) Siccome il file base-setup.html è stato messo nel .gitignore allora
è necessario copiare il template di default con questo comando (nella
riga 35 di Dockerfile): RUN cp
/usr/local/lib/python3.9/site-packages/bootstrap_italia_template/templates/bootstrap-italia-base.html
templates/base-setup.html

3) Per installare gli utenti di test aggiungere la riga in Dockerfile,
come ultimo comando primna dell'expose: RUN python manage.py loaddata
dumps/example_conf.json

Grazie ancora.
Alida


Il giorno ven 25 giu 2021 alle ore 13:51 Giuseppe De Marco
***@***.***> ha scritto:

**Comment by peppelinux** [comment]
Ciao @alidaisolani 
vi andrebbe di fare una PullRequest di riparazione a questo aspetto e figurare tra i contributori del progetto?

**Comment by claudiobat** [comment]
Ciao, vediamo ci provo.

**Comment by peppelinux** [comment]
grazie @claudiobat 
il tuo contributo è stato veramente prezioso
https://github.com/UniversitaDellaCalabria/uniTicket/pull/57
