### ISSUE TITLE
Tasto "Chiudi" Utente

### ISSUE THREAD

**Issue by dodaroe** [UniversitaDellaCalabria/uniTicket#62]
Carissimi,
stiamo riscontrando alcune difficoltà con il tasto "chiudi" sui ticket degli utenti.
Alcuni Utenti, dopo aver inoltrato il ticket, lo chiudono pensando che sia l'ultimo step per inoltrare la richiesta.
Si potrebbe aggiungere una finestra di warning che compare nel momento in cui l'utente clicca sul tasto chiudi in cui si dice che se si conferma l'operazione la richiesta non verrà acquisita dall'operatore?

Grazie

**Comment by francesco-filicetti** [comment]
Si, va bene.
Nei prossimi giorni verrà integrato.
Grazie

**Comment by francesco-filicetti** [comment]
inserito alert per gli utenti

https://github.com/UniversitaDellaCalabria/uniTicket/commit/68c4673d8e6485d6bbcfe88482adbaa3e40f639e

![Selezione_484](https://user-images.githubusercontent.com/28479069/133382236-06af3d9a-b9f7-4dd1-bc4a-1368109d2df8.png)
