### ISSUE TITLE
logout button

### ISSUE THREAD

**Issue by peppelinux** [UniversitaDellaCalabria/uniTicket#68]
![image](https://user-images.githubusercontent.com/1297620/138466285-f686252e-44ad-4d50-8e85-4753244514ac.png)

It would be better to put the button outside of this huge menu

**Comment by francesco-filicetti** [comment]
Solved here https://github.com/UniversitaDellaCalabria/uniTicket/commit/9879a8824880e79a305315383ebb1b2785940e86

![Selezione_513](https://user-images.githubusercontent.com/28479069/140473404-c351d26c-a51b-491c-964b-04fc25bcb080.png)
