### ISSUE TITLE
[Security] Stop using RSA1_5

### ISSUE THREAD

**Issue by peppelinux** [UniversitaDellaCalabria/uniTicket#76]
here
https://github.com/UniversitaDellaCalabria/uniTicket/blob/master/uni_ticket_project/settingslocal.py.example#L295

and also in the documentation, change `RSA1_5` to `RSA-OAEP` or `RSA-OAEP-256`

**Comment by francesco-filicetti** [comment]
solved here https://github.com/UniversitaDellaCalabria/uniTicket/commit/39084e62e2b99db2da2bc5db83fc0b2e7862fc35
