### ISSUE TITLE
Dettagli Tipologia di Richiesta

### ISSUE THREAD

**Issue by tringiu** [UniversitaDellaCalabria/uniTicket#87]
Salve,

è possibile configurare i dettagli delle Tipologie di Richiesta che appaiono nella dashboard?
A noi di Uniparthenope, per esempio, sarebbe utile visualizzare anche se il Ticket è di tipo Notifica.

Grazie

**Comment by peppelinux** [comment]
@francesco-filicetti che ne pensi, posso gestirla nella milestone v2.0.0?

**Comment by francesco-filicetti** [comment]
Certamente

**Comment by peppelinux** [comment]
@tringiu possiamo implementarlo in uniTicket v2.0.0
grazie

questa issue verrà chiusa appena faremo commit sul branch v2.0.0, in previsione del suo rilascio come stabile

**Comment by tringiu** [comment]
Grazie a voi e buon lavoro

**Comment by francesco-filicetti** [comment]
I dati riepilogativi delle tipologie di richiesta includono quelli con un maggiore "impatto" nell'immediato.
La possibilità di customizzare queste informazioni richiederebbe un effort che non sarebbe proporzionato al guadagno finale.
E' stato inserito il flag che indica ai manager se una tipologia di richiesta è di tipo notifica o no

Commit: https://github.com/UniversitaDellaCalabria/uniTicket/commit/e52b98f64e5d617e4f40bf299b3a129af0695e43
