### ISSUE TITLE
Export ticket per invio email con delega

### ISSUE THREAD

**Issue by peppelinux** [UniversitaDellaCalabria/uniTicket#9]
Ogni ticket è un oggetto json.
Sarebbe utile lasciare l'opportunità agli utenti di comporre un modulo di inserimento (ticket) ed esportarlo sotto forma di url copiabile. Inviare questo url via email, out-of-band e in autonomia, al collega/utente/superiore delegato alla creazione.

Il delegato clicca sul link contenuto nella email, questo porta su una risorsa adhoc per la creazione dei ticket.

Caso d'uso:
- la segreteria compila il modulo, lo esporta senza immetterlo nel sistema (nessuna persistenza), e lo invia al "direttore" sottoforma di web link.
- il direttore apre la email, clicca sul link, si autentica su uniticket, accede al modulo precompilato, lo visiona e lo crea.

Nota bene:
- gli allegati non possiamo gestirli. Ovvero potremmo gestirli ma non via HTTP GET, quindi meglio che questi vengano allegati notificati separatamente.

Funzione aggiuntiva:
- In questo caso il direttore otterrà le notifiche riguardanti il ticket, perchè creato da lui. Qualcuno preferirebbe che il Direttore delegasse un incaricato alla ricezione delle notifiche. Questo aspetto è un pò strano... Un direttore che non riceve, non controlla ma pone solo la firma (molto anni '80). Piuttosto che sviluppare il meccanismo di delega sul piano tecnologico, sarebbe meglio affrontarlo organizzativamente. Ovvero un utente che riceve la nomina e crea i ticket a suo nome per delega del direttore.

Proof-of-code della serializzazione
````
import base64
import json

ticket = \
{'code': '324',
 'subject': 'dsfsdfsdfs',
 'description': 'dsfdsfdsfdsfsdfsdf',
 'input_module': 23,
 'modulo_compilato':{
      "telefono": "213123",
      "qualifica_richiedente": "PTA",
      "altro": ""
    }
}

mod_enc = base64.b64encode(json.dumps(ticket).encode())
````

mod_enc verrebbe inviato alla risorsa per l'import del ticket.
esempio:
````
https://uniticket.bla/ticket/new/import?mod_enc=eyJjb2RlIjogIjMyNCIsICJzdWJqZWN0IjogImRzZnNkZnNkZnMiLCAiZGVzY3JpcHRpb24iOiAiZHNmZHNmZHNmZHNmc2Rmc2RmIiwgImlucHV0X21vZHVsZSI6IDIzLCAibW9kdWxvX2NvbXBpbGF0byI6IHsidGVsZWZvbm8iOiAiMjEzMTIzIiwgInF1YWxpZmljYV9yaWNoaWVkZW50ZSI6ICJQVEEiLCAiYWx0cm8iOiAiIn19&format=json
````

Funzione aggiuntiva
format=json potrebbe essere anche format=csv o format=xls.

**Comment by francesco-filicetti** [comment]
solved here https://github.com/UniversitaDellaCalabria/uniTicket/commit/60df13ed6e2dc19da9ebee75b7aee9106cb7dd51
