### ISSUE TITLE
Clausole ticket Anonimi

### ISSUE THREAD

**Issue by tringiu** [UniversitaDellaCalabria/uniTicket#96]
Ciao,

considerando il caso di una tipologia accessibile da utenti autonomi per la quale viene utilizzata una clausola, in cui è presente un allegato.
Quando un utente anonimo vuole aprire una segnalazione, se scarica l'allegato gli viene richiesto il login che è in contrapposizione al ticket anonimo.
Come si può risolvere?

Grazie

**Comment by francesco-filicetti** [comment]
Grazie @tringiu .
Scrivo qui appena l'avrò fixato

**Comment by francesco-filicetti** [comment]
Bug fixato.
Rilasciate v2.2.1 e v1.8.3.
Grazie ancora

**Comment by tringiu** [comment]
Grazie a voi
