### ISSUE TITLE
Invio mail per cambio competenza

### ISSUE THREAD

**Issue by tringiu** [UniversitaDellaCalabria/uniTicket#97]
Ciao,

quando un ticket viene trasferito, per competenza, ad un altro ufficio, non viene inviata la mail di notifica agli operatori dell'ufficio di destinazione.

Grazie

**Comment by francesco-filicetti** [comment]
risolto https://github.com/UniversitaDellaCalabria/uniTicket/commit/f220ce18c0d80ac4658857942f9a7bdf04d73daf
